apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  SecretDbConnectionString: U0VSVkVSPW1zc3FsaW5zdDtEQVRBQkFTRT1UcmlkZW50O1VJRD1zYTtQV0Q9QWRtaW5AOTAxOCM7TE9HSU5fVElNRU9VVD02MA== #"SERVER=mssqlinst;DATABASE=Trident;UID=sa;PWD=Admin@9018#;LOGIN_TIMEOUT=60"