apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa
spec:
  minReplicas: 1
  maxReplicas: 50
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: frontend

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

