apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: demo-storage
  # hostPath:
  #   path: /mnt/data


